name: Android
on:
  push :
    branches : dev
    
jobs:
  Android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: â‡ï¸ Setup Nodejs
        uses: actions/setup-node@v3.5.1
      
      - name: â™¨ï¸ Setup Java
        uses: actions/setup-java@v3.7.0
        with:
          java-version: '17' 
          distribution: oracle
      
      - name: ğŸ— Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          
      - name: ğŸ“¦ Install dependencies
        run: npm install
      
      - name: ğŸŒ€ Build Android APK Bundle
        run: |
          eas init --non-interactive --id ${{ secrets.EXPO_PROJECT_ID }}
          eas build --non-interactive --platform android --profile release
          
      - name: Download APK
        run: | 
          APK=$(eas build:list --limit 1 --non-interactive | grep -o 'https://[^ "<]*.apk')
          echo ${APK}
          curl ${APK} --output app.apk          

      - name: ğŸ”” Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false
      
      - name: ğŸš€ Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app.apk
          asset_name: app.apk
          asset_content_type: application/vnd.android.package-archive
      
      - name: ğŸ Publish release
        uses: StuYarrow/publish-release@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.create_release.outputs.id }}
